### ISSUE TITLE
Record the video

### ISSUE THREAD

**Issue by LIYUHAN22** [DIT113-V22/group-16#12]
As a user I want the camera to record the video.

Acceptance criteria: 

- [ ] The camera should be able to capture video
- [ ] Recorded video is valid and playable even outside of the application.

**Comment by platisd** [comment]
What is the "test" you are referring to? :)

**Comment by LIYUHAN22** [comment]
This test refers to meeting the expectations in the user story, such as the "recorded video" test, where you can see the recorded file and play it. We may change this "test" later to make it more detail.

**Comment by LIYUHAN22** [comment]
> What is the "test" you are referring to? :)

This test refers to meeting the expectations in the user story, such as the "recorded video" test, where you can see the recorded file and play it. We may change this "test" later to make it more detail.

**Comment by platisd** [comment]
The acceptance criteria now look much more concise! :+1:

**Comment by LIYUHAN22** [comment]
Since we found this feature is not easy to achieve and we didn't have enough time, our team decided to give up and close this issue.
