### ISSUE TITLE
Unused sketches in the repository

### ISSUE THREAD

**Issue by platisd** [DIT113-V22/group-16#31]
They should be removed. :warning: 

I am talking about the directories:
* [sprint1](https://github.com/DIT113-V22/group-16/tree/master/sprint1)
* [obstacleAvoidance](https://github.com/DIT113-V22/group-16/tree/master/obstacleAvoidance)

**Comment by LIYUHAN22** [comment]
OK, after we manage the code of our other branches we will remove it

**Comment by platisd** [comment]
This has still not been addressed, [sprint1](https://github.com/DIT113-V22/group-16/tree/master/sprint1) is still there and there were even some changes to it! :warning:

**Comment by platisd** [comment]
Why is [sprint1](https://github.com/DIT113-V22/group-16/tree/master/sprint1) still there? :sweat:

**Comment by LIYUHAN22** [comment]
> Why is [sprint1](https://github.com/DIT113-V22/group-16/tree/master/sprint1) still there? 😓
Sorry, we haven't merged the branch right now. In our newest branch sprint 1 is already been deleted. we will merged the branch this two days

**Comment by platisd** [comment]
If it hasn't been merged it means that it has *not* been done.
Also, how come a removal of a file takes so long? 😅

**Comment by LIYUHAN22** [comment]
> If it hasn't been merged it means that it has _not_ been done. Also, how come a removal of a file takes so long? 😅

Sorry, we haven't merged the latest code to master before, so we haven't fixed this problem.

**Comment by darmacuong** [comment]
Unused sketch deleted.
